const scoringRules = {
  singles: [
    { label: "Each one", face: 1, score: 100 },
    { label: "Each five", face: 5, score: 50 },
  ],
  special: {
    label: "Devil's head",
    effect: "Adds one value to any combination.",
  },
  triples: [
    { face: 1, label: "Three ones", score: 1000 },
    { face: 2, label: "Three twos", score: 200 },
    { face: 3, label: "Three threes", score: 300 },
    { face: 4, label: "Three fours", score: 400 },
    { face: 5, label: "Three fives", score: 500 },
    { face: 6, label: "Three sixes", score: 600 },
  ],
  ofKind: {
    note: "Each additional die after three doubles the value.",
    examples: [
      { label: "Four of a kind", score: 400 },
      { label: "Five of a kind", score: 800 },
      { label: "Six of a kind", score: 1600 },
    ],
  },
  straights: [
    { label: "Straight 1-5", score: 500 },
    { label: "Straight 2-6", score: 750 },
    { label: "Full straight 1-6", score: 1500 },
  ],
};

const diceCatalog = [
  {
    name: "Aranka's die",
    id: "die_aranka",
    description: "Aranka gave me this die to make it easier for me to play against her husband.",
    faces: [28.6, 4.8, 28.6, 4.8, 28.6, 4.8],
  },
  {
    name: "Cautious cheater's die",
    id: "die_Gamblerova_good",
    description: "A die modified by an expert. It is precisely loaded, but also inconspicuous.",
    faces: [23.8, 14.3, 9.5, 14.3, 23.8, 14.3],
  },
  {
    name: "Ci die",
    id: "die_Ci",
    description: "The second in the line of the demonic dice, she likes to get lost, but when she's with her sisters she's very strong.",
    faces: [13, 13, 13, 13, 13, 34.8],
  },
  {
    name: "Devil's head die",
    id: "dieDevil",
    description: "A die that feels hot to the touch. In place of a one it has a devil's head, which is not something folk like to gaze upon...",
    faces: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
    special: "devils-head",
  },
  {
    name: "Die of misfortune",
    id: "dieUnlucky",
    description: "They say that when it rains, it pours. But if you play with this die, the only thing pouring will be your tears.",
    faces: [4.5, 22.7, 22.7, 22.7, 22.7, 4.5],
  },
  {
    name: "Even die",
    id: "dieEven",
    description: "A die loaded in favour of even numbers.",
    faces: [6.7, 26.7, 6.7, 26.7, 6.7, 26.7],
  },
  {
    name: "Favourable die",
    id: "dieFavourable",
    description: "A playing die that brings luck more often than you'd expect.",
    faces: [33.3, 0, 5.6, 5.6, 33.3, 22.2],
  },
  {
    name: "Fer die",
    id: "die_e",
    description: "The third and last in the line of demonic dice.",
    faces: [13, 13, 13, 13, 13, 34.8],
  },
  {
    name: "Greasy die",
    id: "zachranaPtacka_die_klobas",
    description: "A more reliable die than a normal one, but it cannot be relied on for everything.",
    faces: [17.6, 11.8, 17.6, 11.7, 17.6, 23.5],
  },
  {
    name: "Grimy die",
    id: "zachranaPtacka_die_mud",
    description: "One could say it will get you out of the frying pan into the fire. And sometimes it will let you stew in your own juice.",
    faces: [6.2, 31.2, 6.2, 6.2, 43.7, 6.2],
  },
  {
    name: "Grozav's lucky die",
    id: "ZikmunduvTabor_grozavGotchaDie",
    description: "It is actually not all that lucky, but don't tell anyone!",
    faces: [6.7, 66.7, 6.7, 6.7, 6.7, 6.7],
  },
  {
    name: "Heavenly Kingdom die",
    id: "dieKingdomCome",
    description: "A miraculous playing die, sent from the Heavenly Kingdom to the kingdom of men.",
    faces: [36.8, 10.5, 10.5, 10.5, 10.5, 21],
  },
  {
    name: "Holy Trinity die",
    id: "dieHolyTrinity",
    description: "A consecrated die commemorating the Holy Trinity, especially by rolling threes.",
    faces: [18.2, 22.7, 45.4, 4.5, 4.5, 4.5],
  },
  {
    name: "Hugo's die",
    id: "dieSkull",
    description: "A die of the most loyal regular at the Hole. It bears his likeness.",
    faces: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
  },
  {
    name: "King's die",
    id: "die_Kralova",
    description: "An anointed head has no need of a loaded die, since he is always right and can never lose.",
    faces: [12.5, 18.7, 21.9, 25, 12.5, 9.4],
  },
  {
    name: "Lousy gambler's die",
    id: "die_Gamblerova_bad",
    description: "A shoddy loaded die. It's quite noticeably unbalanced.",
    faces: [10, 15, 10, 15, 35, 15],
  },
  {
    name: "Lu die",
    id: "die_Lu",
    description: "The first of the line of demonic dice.",
    faces: [13, 13, 13, 13, 13, 34.8],
  },
  {
    name: "Lucky die",
    id: "dieLucky",
    description: "When fortune smiles on you, smile back. Otherwise you'll look suspicious.",
    faces: [27.3, 4.5, 9.1, 13.6, 18.2, 27.3],
  },
  {
    name: "Mathematician's die",
    id: "die_Matematikova",
    description: "A die loaded based on the work of a forgotten mathematician. It may be better suited to solving equations than playing dice.",
    faces: [16.7, 20.8, 25, 29.2, 4.2, 4.2],
  },
  {
    name: "Molar die",
    id: "dieTeeth_a",
    description: "A die made out of a molar tooth. It's probably better not to know who it came from.",
    faces: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
  },
  {
    name: "Monk's die",
    id: "dieCursed",
    description: "No one knows for sure whether it was blessed by a holy man or just spat on by a drunken monk. Either way, the die rolls... sort of. It's said to bring good luck to honest people. To scoundrels, it brings foolish dreams and a tendency to trip over things that weren't there before. Or maybe it's the other way around.",
    faces: [40, 40, 5, 5, 5, 5],
  },
  {
    name: "Mother-of-pearl die",
    id: "problemovejParchant_pearlDice",
    description: "A rare pink mother-of-pearl die. Said to bring luck in games, but misfortune in love.",
    faces: [25, 8.3, 8.3, 8.3, 25, 25],
  },
  {
    name: "Odd die",
    id: "dieOdd",
    description: "A die loaded to favour odd numbers.",
    faces: [26.7, 6.7, 26.7, 6.7, 26.7, 6.7],
  },
  {
    name: "Ordinary die",
    id: "dieNormal",
    description: "An ordinary playing die.",
    faces: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
  },
  {
    name: "Painted die",
    id: "dieBlue",
    description: "One of the dice coloured using modern techniques that hide the attempt to load it.",
    faces: [18.7, 6.2, 6.2, 6.2, 43.7, 18.7],
  },
  {
    name: "Painter's die B",
    id: "malir_die_b",
    description: "Painter Voyta's blue-painted die.",
    faces: [9.1, 27.2, 18.2, 18.2, 18.2, 9.1],
  },
  {
    name: "Painter's die G",
    id: "malir_die_g",
    description: "Painter Voyta's green-painted die.",
    faces: [9.1, 27.2, 18.2, 18.2, 18.2, 9.1],
  },
  {
    name: "Painter's die R",
    id: "malir_die_r",
    description: "Painter Voyta's red-painted die.",
    faces: [9.1, 27.2, 18.2, 18.2, 18.2, 9.1],
  },
  {
    name: "Pie die",
    id: "die_Kolacova",
    description: "Doesn't look particularly tasty, but it's well balanced towards lower numbers.",
    faces: [46.2, 7.7, 23.1, 23.1, 0, 0],
  },
  {
    name: "Premolar die",
    id: "dieTeeth_b",
    description: "A playing die made from a premolar tooth.",
    faces: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
  },
  {
    name: "Sad Greaser's die",
    id: "zachranaPtacka_die_sad_sergeant",
    description: "A blue die mirroring the sadness of its original owner.",
    faces: [26.1, 26.1, 4.3, 4.3, 26.1, 13],
  },
  {
    name: "Saint Antiochus' die",
    id: "die_Antiocha",
    description: "The Saint Antiochus' die always rolls a 3. Not 2. And especially not 4.",
    faces: [20, 6.7, 40, 6.7, 6.7, 20],
  },
  {
    name: "Shrinking die",
    id: "dieBalanced",
    description: "A very lightly loaded die. One can barely differentiate it from an ordinary die.",
    faces: [22.2, 11.1, 11.1, 11.1, 11.1, 33.3],
  },
  {
    name: "St. Stephen's die",
    id: "die_sarlatan",
    description: "A die blessed by St. Stephen, guaranteeing favourable numbers in the game and protection from loose stones.",
    faces: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
  },
  {
    name: "Strip die",
    id: "dieStripping",
    description: "Legend has it this die will help you undress many a wench.",
    faces: [25, 12.5, 12.5, 12.5, 18.8, 18.8],
  },
  {
    name: "Tengri's die",
    id: "die_Tengri",
    description: "This one appeared to me after I won on all of Tengri's tracks. A little token of my tremendous success, perhaps?",
    faces: [28.5, 14.3, 14.3, 14.3, 14.3, 14.3],
  },
  {
    name: "Trinity die",
    id: "zachranaPtacka_die_trojak",
    description: "For some reason, this die usually rolls a three. Why?",
    faces: [12.5, 6.2, 56.2, 6.2, 12.5, 6.2],
  },
  {
    name: "Unbalanced die",
    id: "dieUnbalanced",
    description: "A playing die someone tried to load to his advantage, but didn't do a very good job.",
    faces: [25, 33.3, 8.3, 8.3, 16.7, 8.3],
  },
  {
    name: "Unlucky die",
    id: "dieAdversity",
    description: "Sometimes Lady Luck is on your side, sometimes she isn't. With this die, she most likely isn't.",
    faces: [9.1, 27.3, 18.2, 18.2, 18.2, 9.1],
  },
  {
    name: "Wagoner's die",
    id: "die_Vozkova",
    description: "According to legend, this die belonged to the famous Roman charioteer Arnuldus, whose tactics consisted of tiring his opponents or lulling them to sleep.",
    faces: [5.6, 27.8, 33.3, 11.1, 11.1, 11.1],
  },
  {
    name: "Weighted die",
    id: "prepadeni_dieBarn",
    description: "A mysterious playing die found in a ruined house. Suspiciously, it tends to land on 1.",
    faces: [66.7, 6.7, 6.7, 6.7, 6.7, 6.7],
  },
  {
    name: "Wisdom tooth die",
    id: "dieTeeth_c",
    description: "A playing die made from a wisdom tooth.",
    faces: [16.7, 16.7, 16.7, 16.7, 16.7, 16.7],
  },
];
